image: python:3.9-bullseye

variables:
  TAGNAME: "continuous-${CI_COMMIT_BRANCH}"

stages:
  - vars
  - build
  - release

vars:
  image: python:3.9
  stage: vars
  script:
    - VERSION=$(cat VERSION)

    - echo "VERSION=$VERSION" > vars.env

    # Wheel
    - >
      echo "WHEEL_FILENAME=${CI_PROJECT_NAME}-${VERSION}-py3-none-any.whl"
      >> vars.env
    - >
      echo "WHEEL_LATEST_FILENAME=${CI_PROJECT_NAME}-latest-py3-none-any.whl"
      >> vars.env
    - >
      echo "WHEEL_ARTIFACT_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/continuous-${CI_COMMIT_BRANCH}/${CI_PROJECT_NAME}-${VERSION}-py3-none-any.whl"
      >> vars.env

    # GemV
    - >
      echo "GEMV_APPIMAGE_FILENAME=GemV-${VERSION}-x86_64.AppImage"
      >> vars.env
    - >
      echo "GEMV_APPIMAGE_LATEST_FILENAME=GemV-latest-x86_64.AppImage"
      >> vars.env
    - >
      echo "GEMV_APPIMAGE_ARTIFACT_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/continuous-${CI_COMMIT_BRANCH}/GemV-${VERSION}-x86_64.AppImage"
      >> vars.env

    # Gemalaya
    - >
      echo "GEMALAYA_APPIMAGE_FILENAME=Gemalaya-${VERSION}-x86_64.AppImage"
      >> vars.env
    - >
      echo "GEMALAYA_APPIMAGE_LATEST_FILENAME=Gemalaya-latest-x86_64.AppImage"
      >> vars.env
    - >
      echo "GEMALAYA_APPIMAGE_ARTIFACT_URL=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/continuous-${CI_COMMIT_BRANCH}/Gemalaya-${VERSION}-x86_64.AppImage"
      >> vars.env

  artifacts:
    reports:
      dotenv: vars.env

build:
  stage: build
  only:
    - master
    - devel
    - viewer
    - /^gemalaya/ 
  script:
    - echo 'deb http://deb.debian.org/debian bullseye main contrib non-free' >> /etc/apt/sources.list
    - apt-get -y update
    - apt-get install -y zip fuse libttspico-utils
    - apt-get install -y libxcb-xkb1 libxkbcommon-x11-0 libxcb-cursor0
    - apt-get install -y libxcb-util1 libxcb-image0 libxcb-randr0 libxcb-keysyms1 libxcb-icccm4 libxcb-render0 libxcb-xfixes0 libxcb-keysyms1 libxcb-shape0 libxcb-render-util0 libxcb-image0

    - python3 -m pip install --upgrade pip
    - python3 -m venv venv
    - source venv/bin/activate

    - pip install wheel
    - pip install '.[ui,gemalaya]'
    - python setup.py build_gemalaya bdist_wheel

    - ./ci/gemv-appimage-build
    - ./ci/gemalaya-appimage-build

  artifacts:
    paths:
      - "*.AppImage"
      - dist/*.whl

release:
  image: registry.gitlab.com/gitlab-org/release-cli
  stage: release
  only:
    - master
    - devel
    - viewer
    - /^gemalaya/ 
  script:
    - apk add curl

    - >
      curl
      --request DELETE
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --header "PRIVATE-TOKEN: ${GITLAB_PRIVATE_TOKEN}"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${TAGNAME}"

    - >
     curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
     --upload-file
     dist/${WHEEL_FILENAME}
     ${WHEEL_ARTIFACT_URL}

    - >
     curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
     --upload-file
     ${GEMV_APPIMAGE_FILENAME}
     ${GEMV_APPIMAGE_ARTIFACT_URL}

    - >
     curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
     --upload-file
     ${GEMALAYA_APPIMAGE_FILENAME}
     ${GEMALAYA_APPIMAGE_ARTIFACT_URL}

    - >
      release-cli create
      --name release-${CI_COMMIT_SHA}
      --description README.md
      --tag-name $TAGNAME
      --ref $CI_COMMIT_SHA
      --assets-link
      "{\"name\": \"${WHEEL_FILENAME}\", \"filepath\": \"/${WHEEL_LATEST_FILENAME}\", \"url\": \"${WHEEL_ARTIFACT_URL}\"}"
      --assets-link
      "{\"name\": \"${GEMV_APPIMAGE_FILENAME}\", \"filepath\": \"/${GEMV_APPIMAGE_LATEST_FILENAME}\", \"url\": \"${GEMV_APPIMAGE_ARTIFACT_URL}\"}"
      --assets-link
      "{\"name\": \"${GEMALAYA_APPIMAGE_FILENAME}\", \"filepath\": \"/${GEMALAYA_APPIMAGE_LATEST_FILENAME}\", \"url\": \"${GEMALAYA_APPIMAGE_ARTIFACT_URL}\"}"
