#!/bin/bash

PYSIDE6_ADDONS_WHL_URL="https://files.pythonhosted.org/packages/d1/57/d0e00aafa280ca4bea4a41e52138f9c0b5db13ef31624c3ed33a95de823a/PySide6_Addons-6.5.2-pp39-pypy39_pp73-manylinux_2_28_x86_64.whl"

if [ ! -f "python3.9.13-cp39-cp39-manylinux2010_x86_64.AppImage" ]; then
    wget https://github.com/niess/python-appimage/releases/download/python3.9/python3.9.13-cp39-cp39-manylinux2010_x86_64.AppImage
fi

if [ -d squashfs-root ]; then
    rm -rf squashfs-root
fi

# Extract this AppImage
chmod +x python*-manylinux2010_x86_64.AppImage
./python*-manylinux2010_x86_64.AppImage --appimage-extract

APPDIR="$PWD/squashfs-root"

./squashfs-root/AppRun -m pip install -U pip
./squashfs-root/AppRun -m pip install '.[gemalaya,gemalaya-http-proxy]'
python setup.py build_gemalaya install

# Get the pyside6-addons wheel and unpack the QtMultimedia files from it
# so that the QML multimedia plugin can be loaded in gemalaya
PYSIDE6_ADDONS_WHL="$PWD/pyside6_addons.whl"

if [ ! -f "$PYSIDE6_ADDONS_WHL" ]; then
    curl -o $PYSIDE6_ADDONS_WHL $PYSIDE6_ADDONS_WHL_URL
fi

qtmultilist="PySide6/QtMultimedia.pyi
PySide6/QtMultimedia.pypy39-pp73-x86_64-linux-gnu.so
PySide6/QtMultimediaWidgets.pyi
PySide6/QtMultimediaWidgets.pypy39-pp73-x86_64-linux-gnu.so
PySide6/Qt/lib/libQt6Multimedia.so.6
PySide6/Qt/lib/libQt6MultimediaQuick.so.6
PySide6/Qt/lib/libQt6MultimediaWidgets.so.6
PySide6/Qt/qml/QtMultimedia/Video.qml
PySide6/Qt/qml/QtMultimedia/libquickmultimediaplugin.so
PySide6/Qt/qml/QtMultimedia/plugins.qmltypes
PySide6/Qt/qml/QtMultimedia/qmldir
PySide6/Qt/plugins/multimedia/libffmpegmediaplugin.so
PySide6/Qt/plugins/multimedia/libgstreamermediaplugin.so
PySide6/typesystems/typesystem_multimedia.xml
PySide6/typesystems/typesystem_multimediawidgets.xml
"

pushd squashfs-root/opt/python3.9/lib/python3.9/site-packages
unzip $PYSIDE6_ADDONS_WHL $qtmultilist
popd

rm -f squashfs-root/AppRun
cp ci/AppRun.gemalaya ./squashfs-root/AppRun

GPLP="$PWD"/squashfs-root/GemPubLibrary
mkdir -p $GPLP

rm squashfs-root/usr/share/applications/python3.9.*.desktop
rm squashfs-root/usr/share/metainfo/*.appdata.xml
mkdir -p squashfs-root/usr/share/metainfo
cp gemalaya.desktop squashfs-root/usr/share/applications/gemalaya.desktop
cp io.gitlab.gemgemgem.Gemalaya.appdata.xml squashfs-root/usr/share/metainfo
rm squashfs-root/*.desktop
cp squashfs-root/usr/share/applications/*.desktop squashfs-root/

# Add icon
mkdir -p squashfs-root/usr/share/icons/hicolor/128x128/apps/
cp gemv.png squashfs-root/usr/share/icons/hicolor/128x128/apps/
cp gemv.png squashfs-root/io.gitlab.gemgemgem.Gemalaya.png
cp squashfs-root/usr/share/icons/hicolor/128x128/apps/gemv.png squashfs-root/

# cleanup
rm -rf squashfs-root/opt/python3.9/include
rm -rf squashfs-root/opt/python3.9/bin/rst*
rm -rf squashfs-root/opt/python3.9/lib/python3.9/ctypes/test
rm -rf squashfs-root/opt/python3.9/lib/python3.9/distutils/tests
rm -rf squashfs-root/opt/python3.9/lib/python3.9/idlelib
rm -rf squashfs-root/opt/python3.9/lib/python3.9/lib2to3
rm -rf squashfs-root/opt/python3.9/lib/python3.9/ensurepip
rm -rf squashfs-root/opt/python3.9/lib/python3.9/tkinter

rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/lxml
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/bs4/tests
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/kivy/tests
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/pip
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/setuptools

rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/PySide6/lupdate
rm -rf squashfs-root/opt/python3.9/lib/python3.9/site-packages/PySide6/Qt/translations/*{fi,nl,pl,ko,cs,ru,sk,zh,ar,pt}*

rm -rf squashfs-root/usr/share/tcltk
rm -rf squashfs-root/usr/lib/libtk*
rm -rf squashfs-root/usr/lib/libtcl*
find squashfs-root | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf

sed -i -e 's/#\!\/.*$/#!\/opt\/python3.9\/bin\/python3.9/' \
    squashfs-root/opt/python3.9/bin/gemalaya
sed -i -e 's/#\!\/.*$/#!\/opt\/python3.9\/bin\/python3.9/' \
    squashfs-root/opt/python3.9/bin/levior

export VERSION=$(cat squashfs-root/opt/python3.9/lib/python3.9/site-packages/gemgemgem-*.dist-info/METADATA | grep "^Version:.*" | cut -d " " -f 2)

wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
chmod +x appimagetool*.AppImage

./appimagetool-x86_64.AppImage squashfs-root/
