debug: false

gemini:
  timeout_default: 15

levior:
  enable: true
  cache_enable: true

ui:
  # active theme name
  theme: 'sinister'

  # edition timeout (ms) for the address bar, completions are shown after that
  urlCompletionTimeout: 800

  keybSeqTimeout: 600

  # open web URLs with the webbrowser module
  openUnsupportedUrls: false

  # Settings for the QML flickable item that contains the gemini page
  page:
    # The rate at which a flick will decelerate
    # The higher the number, the faster it slows down when the user
    # stops flicking via keyboard, touch, touchpad or mouse wheel.
    flickDeceleration: 600

    # In pixels per second, this sets the maximum velocity with which the
    # user can flick the view
    maximumFlickVelocity: 2400

    # In pixels per second, determines how much we flick the page
    # up and down when the "up" or "down" keys are pressed
    downFlickPPS: -350
    upFlickPPS: 350

    # In pixels per second, determines how much we flick the page
    # up and down when the "page up" or "page down" keys are pressed
    pageDownFlickPPS: -1200
    pageUpFlickPPS: 1200

    # Scroll to the item that gets the focus in the page when you press Tab
    scrollToItemOnFocus: true

    # Maximum number of gemtext "items" to process in a row
    maxItemsPerPageSection: 1024

  # per-mimetype configuration (uses regexps)
  mimeConfig:
    # Config for common image formats
    image/(jpg|jpeg|pcx|png|tiff|webp|svg):
      autoPreview: false

  # Font sizes
  fonts:
    defaultPointSize: 12

    text:
      pointSize: 12

    preformattedText:
      pointSize: 12

    links:
      pointSize: 14
      shortcutFontSize: 16

  # Shortcuts
  shortcuts:
    openConfigDialog: 'F12'
    bookmark: 'Ctrl+d'
    quit: 'Ctrl+q'
    themesCycle: 'Ctrl+y'

    # URLs
    urlEdit: 'Ctrl+l'

    # History
    historyBack: 'Ctrl+backspace'

    linkOpenTargetSwitch: 'Ctrl+o'

    pageReload: 'Ctrl+r'

    # Font size
    fontSizeIncrease: 'Ctrl++'
    fontSizeDecrease: 'Ctrl+-'

    # Stack
    stackCycle: 'Ctrl+Tab'
    stackCreateSpace: 'Ctrl+t'
    stackCloseSpace: 'Ctrl+w'
    stackPrevious: 'Ctrl+b'
    stackNext: 'Ctrl+n'
