debug: false

gemini:
  timeout_default: 15

levior:
  enable: true
  cache_enable: true

ui:
  # active theme name
  theme: 'sinister'

  # edition timeout (ms) for the address bar, completions are shown after that
  urlCompletionTimeout: 800

  keybSeqTimeout: 600

  # open web URLs with the webbrowser module
  openUnsupportedUrls: false

  page:
    stepBig: 0.1
    stepSmall: 0.02

  # Font sizes
  fonts:
    defaultPointSize: 12

    text:
      pointSize: 12

    preformattedText:
      pointSize: 12

    links:
      pointSize: 14
      shortcutFontSize: 16

  # Shortcuts
  shortcuts:
    bookmark: 'Ctrl+d'
    quit: 'Ctrl+q'
    themesCycle: 'Ctrl+y'

    # URLs
    urlEdit: 'Ctrl+l'

    # History
    historyBack: 'Ctrl+backspace'

    linkOpenTargetSwitch: 'Ctrl+o'

    pageReload: 'Ctrl+r'

    fontSizeIncrease: 'Ctrl++'
    fontSizeDecrease: 'Ctrl+-'

    stack:
      cycle: 'Ctrl+Tab'
      create: 'Ctrl+t'
      close: 'Ctrl+w'

      previous: 'Ctrl+b'
      next: 'Ctrl+n'
