debug: false

gemini:
  timeout_default: 15

levior:
  enable: true
  cache_enable: true

updates:
  # AppImage check updates mode (manual, automatic, never)
  check_updates_mode: 'manual'

ui:
  # active theme name
  theme: 'sinister'

  # edition timeout (ms) for the address bar, completions are shown after that
  urlCompletionTimeout: 800

  keybSeqTimeout: 600

  # open web URLs with the webbrowser module
  openUnsupportedUrls: false

  # Show the link's URL when a link is focused
  showLinkUrl: false

  # Settings for the QML flickable item that contains the gemini page
  page:
    # The rate at which a flick will decelerate
    # The higher the number, the faster it slows down when the user
    # stops flicking via keyboard, touch, touchpad or mouse wheel.
    flickDeceleration: 600

    # In pixels per second, this sets the maximum velocity with which the
    # user can flick the view
    maximumFlickVelocity: 2400

    # In pixels per second, determines how much we flick the page
    # up and down when the "up" or "down" keys are pressed
    downFlickPPS: -350
    upFlickPPS: 350

    # In pixels per second, determines how much we flick the page
    # up and down when the "page up" or "page down" keys are pressed
    pageDownFlickPPS: -1200
    pageUpFlickPPS: 1200

    # Scroll to the item that gets the focus in the page when you press Tab
    scrollToItemOnFocus: true

    # Maximum number of gemtext "items" to process in a row
    maxItemsPerPageSection: 1024

  # per-mimetype configuration (uses regexps)
  mimeConfig:
    # Config for common image formats
    image/(jpg|jpeg|pcx|png|tiff|webp|svg):
      autoPreview: false

  # Text-to-speech configuration
  tts:
    enabled: false

    # TTS engine. Supported engines: picotts, nanotts, gtts
    engine: 'nanotts'

    readSlowly: false
    autoPlay: true

    # Default gtts TLD
    # https://gtts.readthedocs.io/en/latest/module.html#localized-accents
    defaultTld: 'com'

    # Default audio playback rate
    playbackRate: 1.0

    # Lifetime (in days) for cached TTS files
    mp3CacheForDays: 5

    # Options specific to nanotts
    nanotts_options:
      pitch: 100
      speed: 100
      volume: 40

  translate:
    enabled: false

    targetLangs:
      es:
        prio: 30
      fr:
        prio: 31
      it:
        prio: 32
      de:
        prio: 33
      en:
        prio: 34

  # Font sizes
  fonts:
    defaultPointSize: 12

    text:
      pointSize: 12

    preformattedText:
      pointSize: 12

    links:
      pointSize: 14
      pointSizeUrl: 10
      shortcutFontSize: 16

  # Shortcuts
  shortcuts:
    openConfigDialog: 'F12'
    bookmark: 'Ctrl+d'
    quit: 'Ctrl+q'
    themesCycle: 'Ctrl+y'

    # URLs
    urlEdit: 'Ctrl+l'

    # History
    historyBack: 'Ctrl+backspace'

    linkOpenTargetSwitch: 'Ctrl+o'

    pageReload: 'Ctrl+r'
    pageTextSearch: 'Ctrl+f'

    # Font size
    fontSizeIncrease: 'Ctrl++'
    fontSizeDecrease: 'Ctrl+-'

    # Misfin
    misfinCompose: 'Ctrl+m'

  # Stack Layout Shortcuts
  stackShortcuts:
    stackCycle: 'Ctrl+Tab'
    stackCreateSpace: 'Ctrl+t'
    stackCloseSpace: 'Ctrl+w'
    stackPrevious: 'Ctrl+b'
    stackNext: 'Ctrl+n'

    stackSave1: 'Shift+F1'
    stackLoad1: 'Ctrl+F1'

    stackSave2: 'Shift+F2'
    stackLoad2: 'Ctrl+F2'

  linksShortcuts:
    downloadObject: 'Ctrl+s'
    openInNewSpace: 'n'

  textItemShortcuts:
    translateText: 't'
    translateChangeLanguage: 'l'

  ttsPlayerShortcuts:
    playbackRateIncrease: 'x'
    playbackRateDecrease: 'z'

# Rules to expand URLs
urlCommander:
  # Run a search on geminispace.info
  gsInfoSearch0:
    match: '^gs\s+(.+)\s*$'
    to: 'gemini://geminispace.info/search?\1'

  # General search with auragem
  auraGemSearch0:
    match: '^a\s+(.+)\s*$'
    to: 'gemini://auragem.letz.dev/search/s?\1'

  # MIME-type search with auragem
  auraGemMimeSearch0:
    match: '^am\s+([\w0-9\/]+)\s*$'
    to: 'gemini://auragem.letz.dev/search/mimetype?\1'

  # hidden.nexus post
  hiddenNexusPost0:
    match: '^hnp\s+(.+)\s*$'
    to: 'gemini://hidden.nexus/post/write?\1'

  # User Post on BBS
  bbsUserPost0:
    match: '^bbsup\s+([\w\s_]+)\s+(.+)$'
    to: 'gemini://bbs.geminispace.org/u/\1/post?\2'

savedStacks: {}
