debug: false

gemini:
  timeout_default: 15

ui:
  # active theme name
  theme: 'sinister'

  # edition timeout (ms) for the address bar, completions are shown after that
  urlCompletionTimeout: 800

  keybSeqTimeout: 600

  # open web URLs with the webbrowser module
  openUnsupportedUrls: false

  page:
    stepBig: 0.1
    stepSmall: 0.02

  # Shortcuts
  shortcuts:
    bookmark: 'Ctrl+d'
    quit: 'Ctrl+q'

    # URLs
    urlEdit: 'Ctrl+l'

    # History
    historyBack: 'Ctrl+backspace'

    linkOpenTargetSwitch: 'Ctrl+o'

    stack:
      cycle: 'Ctrl+Tab'
      create: 'Ctrl+t'
      close: 'Ctrl+w'

      previous: 'Ctrl+b'
      next: 'Ctrl+n'
